name = "vless-edgetunnel"
main = "src/index.js"
compatibility_date = "2024-09-23"
workers_dev = true

routes = [
	{ pattern = "vpn.duar.eu.cc", custom_domain = true }
]

[vars]
UUID = "91ade0d4-a4c8-4dde-b2b3-1365853b70ce"
PROXYIP = "proxyip.fxxk.dedyn.io"
